- README.md
> Testing pull request :)

- source/includes/_getting-started.md.erb
- source/includes/api/auth/_auth-step.md.erb
- source/includes/api/auth/_auth.md.erb
- source/includes/api/client/_create-token.md.erb
- source/includes/api/client/_create.md.erb
- source/includes/api/company/_search.md.erb
- source/includes/api/payment/_add.md.erb
- source/includes/api/payment/_assign.md.erb
- source/includes/api/payment/_schedule.md.erb
- source/includes/api/payment/_settings.md.erb
- source/includes/api/swap/_create.md.erb
This header seems to be required, so I added it to the docs.
> Add required application/json header

- .travis.yml
- source/includes/events/_auth.created.md.erb
> Testing out production deploy

- .travis.yml
> Fixing deploy script

- .travis.yml
- Gemfile
- deploy.sh
> Updated ruby version

- .travis.yml
- Gemfile
- deploy.sh
> testing prod build

- .travis.yml
- Gemfile
- Gemfile.lock
- deploy.sh
> Updating for PR merge deploy

- Gemfile.lock
- README.md
- source/includes/events/_swap.success.md.erb
- source/index.html.md.erb
Added Successful Swap event documentation
> BDCS-167 - Added Successful Swap event documentation

- source/includes/_getting-started.md.erb
- source/includes/api/auth/_answer-questions.md.erb
- source/includes/api/payment/_cancel.md.erb
- source/includes/api/payment/index.md.erb
- source/index.html.md.erb
> Updated API docs

- source/includes/products/biller-direct.md.erb
- source/includes/products/connect.md.erb
> Session idleness docs BDCS-402

- source/includes/api/changelog/_index.md.erb
- source/includes/products/connect.md.erb
- source/includes/products/integration.md.erb
- source/index.html.md.erb
> BDCS-484 & BDCS-516 - Changelog, example code, fix error with events

- config.rb
- source/includes/api/changelog/_index.md.erb
- source/includes/api/client/_create-token.md.erb
- source/includes/api/client/_create.md.erb
- source/includes/products/connect.md.erb
> BDCS-515 - userPresenceIsRequired documentation

- source/includes/_introduction.md.erb
- source/includes/_rsa-encryption.md.erb
- source/includes/api/changelog/_index.md.erb
- source/includes/api/client/_create-token.md.erb
- source/includes/api/client/_create.md.erb
- source/includes/events/_auth.created.md.erb
- source/includes/events/_auth.failed.md.erb
- source/includes/events/_auth.hold.md.erb
- source/includes/events/_auth.invalid.md.erb
- source/includes/events/_auth.mfa.md.erb
- source/includes/events/_auth.success.md.erb
- source/includes/events/_bill.created.md.erb
- source/includes/events/_bill.payment.failed.md.erb
- source/includes/events/_bill.payment.sent.md.erb
- source/includes/events/_bill.update.md.erb
- source/includes/events/_object.md.erb
- source/includes/events/_swap.success.md.erb
- source/includes/products/connect.md.erb
- source/index.html.md.erb
> BDCS-660 Updates to documentation

- config.rb
- source/includes/_introduction.md.erb
- source/includes/api/changelog/_index.md.erb
- source/includes/events/_bill.created.md.erb
- source/includes/events/_bill.payment.failed.md.erb
- source/includes/events/_bill.payment.scheduled.md.erb
- source/includes/events/_bill.payment.sent.md.erb
- source/includes/products/biller-direct.md.erb
- source/includes/products/cardswap.md.erb
- source/includes/products/connect.md.erb
- source/includes/products/integration.md.erb
- source/index.html.md.erb
> Bdcs 808 q2open URL and misc. updates for JHA

- source/includes/api/bill/_object.md.erb
- source/includes/api/changelog/_index.md.erb
- source/includes/api/payment/_add.md.erb
- source/includes/api/payment/_list.md.erb
- source/includes/api/payment/_object.md.erb
- source/includes/api/swap/_object.md.erb
- source/includes/events/_bill.payment.failed.md.erb
- source/includes/events/_swap.success.md.erb
BDCS-951 Added in documentation for new swap elements
> BDCS-951 Added in documentation for new swap elements

- source/includes/events/_bill.payment.cancelled.md.erb
- source/includes/events/_bill.update.md.erb
- source/index.html.md.erb
> BDCS-917 Added API docs for bill.payment.cancelled event

- source/includes/events/_swap.success.md.erb
> BDCS-1265 Update swap.success JSON

- source/includes/events/_bill.payment.cancelled.md.erb
> updated API doc

- source/includes/_rsa-encryption.md.erb
> BDCS-1791 Updated for RSA signing

- source/includes/_rsa-encryption.md.erb
> BDCS-1790 fixed typo

- source/includes/api/changelog/_index.md.erb
- source/includes/events/_bill.created.md.erb
- source/includes/events/_bill.payment.cancelled.md.erb
- source/includes/events/_bill.payment.scheduled.md.erb
- source/includes/events/_bill.scheduled-payment-notice.md.erb
- source/includes/events/_swap.success.md.erb
- source/index.html.md.erb
> BDCS-1998 Scheduled payment notice

- source/includes/api/changelog/_index.md.erb
- source/includes/api/swap/_status.md.erb
> promote to prod

- source/includes/_rsa-encryption.md.erb
> BDCS-2022 Update to correct encryption scheme

- source/includes/events/_bill.update.md.erb
Add due date to bill update event
> BDCS-2227 Add due date to bill update event

- source/includes/api/changelog/_index.md.erb
- source/includes/events/_auth.deleted.md.erb
- source/includes/events/_auth.success.md.erb
- source/index.html.md.erb
> BDCS-2303 Add auth.deleted event

- deploy.sh
> Fixed typo in bundler for forced gem install.

- source/includes/_errors.md.erb
- source/includes/api/auth/_hold-codes.md.erb
- source/includes/api/auth/_status.md.erb
- source/index.html.md.erb
- source/stylesheets/_main.scss
> BDCS-2628 Add auth hold codes section

- source/includes/api/client/_create-token.md.erb
> BDCS-2919 Adding nonce documentation back

- source/includes/_errors.md.erb
- source/includes/_rsa-encryption.md.erb
- source/includes/api/changelog/_index.md.erb
> BDCS-3348 Message security documentation updates for AES/RSA changes

- source/includes/_rsa-encryption.md.erb
> BDCS-3390 Tweak API docs

- source/includes/api/client/_create.md.erb
- source/includes/api/client/_sync.md.erb
- source/index.html.md.erb
> BDCS-3450 Add sync client docs

- source/includes/api/client/_sync.md.erb
> BDCS-3450 Wrong url endpoint

- source/includes/api/client/_sync.md.erb
> BDCS-3450 Add card code example

- source/includes/events/_index.md.erb
- source/includes/products/_sessions.md.erb
- source/index.html.md.erb
> BDCS-3457 Add session docs

- source/includes/api/partner/_public-key-latest.md.erb
- source/includes/api/partner/_public-key.md.erb
- source/includes/api/partner/_public-keys.md.erb
- source/index.html.md.erb
> BDCS-3483 Add documentation for new RSA key format and endpoints

- source/includes/api/partner/_public-key.md.erb
> BDCS-3487 Fixed typo

- .gitignore
- package-lock.json
- package.json
> [BDCS-3489] Adding issue prepender

- source/includes/api/client/_create-token.md.erb
- source/includes/api/client/_sync.md.erb
> BDCS-3482 Add cards to response of sync client

- source/includes/api/client/_sync.md.erb
> BDCS-3503 Add cardType and cardBrand

- config.rb
- source/includes/products/cardswap.md.erb
- source/includes/products/connect.md.erb
- source/includes/products/integration.md.erb
> BDCS-3576 Add CardSwap events

- source/includes/api/auth/_hold-codes.md.erb
- source/includes/api/auth/_status.md.erb
- source/includes/api/changelog/_index.md.erb
- source/includes/events/_auth.deleted.md.erb
- source/includes/events/_auth.hold.md.erb
- source/includes/events/_auth.invalid.md.erb
- source/includes/events/_auth.needs-resync.md.erb
- source/includes/events/_auth.success.md.erb
- source/includes/events/_object.md.erb
- source/includes/events/_swap.success.md.erb
> [BDCS-3600] Fixed up docs to match event information better

- source/includes/api/partner/_public-key-latest.md.erb
- source/includes/api/partner/_public-key.md.erb
- source/includes/api/partner/_public-keys.md.erb
> [BDCS-3581] Fixed up docs for tweaks to JWK output

- source/includes/events/_webhook.security.md.erb
> [BDCS-3780] Added webhook security info
